# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "D1bqynNvxi7s+ycBzWuQHt1AyTH8lTQgHl+u6vxnu9KXSTr5v0z2dbwE91PDw9ldEn1A+bJ+46w6oRTX7siXsVnunYGiqoQFr8VxFVzlfbFi2OsWlHKX0JY/gEXvEpL7dmRqqLhLZ5KlI+FQM+cdiTLtUKDqNeiyzfr28XRgCZrYfvDecOc1pjI5vnc8CyF4DAfbYl95pwMoTmN/rn9PAZAthAoOp5K0QURGJ/Qb9784iLGzYTuyiO38zcsleW03mVkcNXADr/zlYA06YzmFDIZszqdGMZDZITQwEajdfgnZko98Nljy0nGlZhxQ3hsLD6gyLM0JYeSiP5RNCxMBiR7NyRVRAwYio5Z0DD3pEZclMElqah+paGQP1/fnzcMJ5jbwtAvieJyxOptfmv/HwXggQyzMapHoTH1YPtdwISjLlUikQqn8HVkf4uhm4oRDbTchp2yCx/zEN5Zs2cK6UwpLajpUgUMP1JuhAiVZr3QkNyuRhr9DNdyRKCu3bDjKNb9ClMPems54otGblUSSUdHKZyj0RYQkK2Jx/DdqjFMo22KZz5p7wI6KgtToV+aRI/GIg5bwqpWwhoXUj3OVtVmurlnVR9mHe5WLDBh1hqYd70QncmF+GFCxCCif1qVQPFGjWrSrcK7JW8pw3j/BAuCajReDV3CJt75S9bffupU="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_mpimpichtarget_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

    - env: CONFIG=linux_ppc64le_mpinompitarget_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

    - env: CONFIG=linux_ppc64le_mpiopenmpitarget_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi