travis:
  secure:
    BINSTAR_TOKEN: mOCBtkwGz0cOvpOE5DK+MAdSjvEsFT0/Aw+TkGvUFdgbNIM2F2zA/TSsIczx2huCvzjAGkRAeRePXhBrjr95YcBW1FFlQ0dgnqUGwHzjZrlmADgZo30Mo5rTtN86fgpZQ3PQtGVpIrxiZtSmiQXrcp9h/LvRJGeycq0h0PnLD29pfc9TfKiGCl4F01WIq0nbIX2STXexAXqy3lGQSS/O1TIe2vTLKWzPrfVmU1LsN8bO4MdTW35uzhW8z6kya2sTFQtvqFAe720OhwtL/5czszkJGHUE9XVYDCDKlX4EFQAkO+cbaRYi9KeUS7pmieqUaqivSXP9+97lJrgjYncUoOIxFkoBDTnNjZ5A82v1QcJSmlF/34py27UQ/2tvD5lWeCK0sxEiObZjgzq6UEvnalXCgYe6pK3axXozKyoqebqj2LRWjBHlMHuCE/KKYUz1tHw4gyPNgi2KK0OX49S6UU+jt8IL5aS44BE+qVx9B3Ump24Qm3lqawX0xz5EOzdCVqlRwG8bOKHwAUVDfIR7jjIW/L8OxqN6E9V3RECIhMlbQG605F2n14LpMD3UFoeKaq3IZ1sKYLaF/JG+4QcOX81fbN1bNn0AywkRSaARM6dS0xJGQRplJJ17RY9AlUR5nRoXk3wSUel1GAF1BRxL0F89ofybA6DMmfFlTVUjLqs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
